-- Migration 005: Disable RLS for Feed Compatibility
BEGIN;

ALTER TABLE predictions DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE advertisements DISABLE ROW LEVEL SECURITY;
ALTER TABLE ad_events DISABLE ROW LEVEL SECURITY;

COMMIT;
